### ISSUE TITLE
Proxy error

### ISSUE THREAD

**Issue by Faiqrana** [bradtraversy/contact-keeper#13]
in your course,, in lesson no 59, when you register user and get data in your state user and isAuthenticated,, i get isAuthenticated true but user does not get filled it at first register,, but when i call loadUser in Home component and refresh then the data is loaded to the state in user and isAuthenticated.

**Comment by musebe** [comment]
Am also facing the same error. The user is not being loaded

**Comment by Faiqrana** [comment]
I've fixed this error,, let me know if you need help

**Comment by musebe** [comment]
I need help please

**Comment by Faiqrana** [comment]
umm how could i help you ? can i see your code?

**Comment by musebe** [comment]
Added you to the codebase

**Comment by Faiqrana** [comment]
i can locate your server.js file

**Comment by Faiqrana** [comment]
install cors in your terminal
then in your server.js write the following code
var cors = require(cors)
app.use(cors())

**Comment by musebe** [comment]
Thats only the frontend. The backend is already hosted.

**Comment by Faiqrana** [comment]
use concurrently to run both servers at the same time

**Comment by bushblade** [comment]
This doesn't seem to be an issue with the repo code so I'm closing.
