### ISSUE TITLE
Should match id with Id of mongoDB _id

### ISSUE THREAD

**Issue by CodingOni** [bradtraversy/contact-keeper#2]
const deleteContact = async _id => {
    try {
      await axios.delete(`/api/contacts/${_id}`);

      dispatch({
        type: DELETE_CONTACT,
        payload: _id
      });
    } catch (err) {
      dispatch({
        type: CONTACT_ERROR,
        payload: err.response.msg
      });
    }
  };

//ContactState.js

**Comment by pranjaljately** [comment]
Would not really call this an issue as that is the parameter. The argument being passed is as follows: `deleteContact(_id)` which means the parameter in the method could really be named anything and personally I would rather use `id` instead of `_id` in the method declaration.

**Comment by bushblade** [comment]
Due to lack of information and clarity I'm closing this issue.
