### ISSUE TITLE
cannot ready property map of undefined

### ISSUE THREAD

**Issue by remymumoh** [bradtraversy/contact-keeper#20]
Contacts
D:/Projects/webprojects/contacts/client/src/components/contacts/Contacts.js:15

```
 }
 return (
<Fragment>
  {filtered !== null ? filtered.map(contact => (
<ContactItem key={contact.id} contact={contact} />
```
the code
```
const contactContext = useContext(ContactContext);

const { contacts, filtered } = contactContext;

if (contacts.length === 0) {
return <h4>please add a contact</h4>;
}

return (
<Fragment>
{filtered !== null
? filtered.map(contact => (
<ContactItem key={contact.id} contact={contact} />
))
: contacts.map(contact => (
<ContactItem key={contact.id} contact={contact} />
))}
</Fragment>
);
};

export default Contacts;
```

what am i missing?

**Comment by bushblade** [comment]
Hi @remymumoh.
Is this a problem you're facing with your own implementation of the project or with the current code in the repository?
If it's a issue you're having in the course then please post in the course Q&A and one of us will help you out.
I'm not entirely sure what your issue is here, please clarify.

**Comment by remymumoh** [comment]
hi bushblade, i cant post on Q&A as i am using a corporate account to access the course, 

am going through your course react front end to back on udemy, i am stuck on section 8, client setup and contacts ui tutorial 58 contact filter.  state i have done everything correctly the code compiles well on the ide but on browser throws error

**Comment by bushblade** [comment]
Hi.
The course Q&A should be available to you.
It's only not available in free courses.
I'll close this as an issue here on GitHub as it's not an issue with the project's code.
