### ISSUE TITLE
Missing loading-prop in ContactState.js

### ISSUE THREAD

**Issue by nikbrunner** [bradtraversy/contact-keeper#23]
Hi Brad,

first of all, thank you for your hard work and for just being a good human. 

I am doing this course right now and noticed that in [this block](https://github.com/bradtraversy/contact-keeper/blob/c7fd157f2307cecbbef983f4848deed66ec58f87/client/src/context/contact/ContactState.js#L19) of `ContactState.js` the `loading: true` property is missing. We set `loading: false` in `contactReducer.js` and query this prop in `Contacts.js` but it will always be `undefined`.

I cloned the repo, created a new branch, added the necessary lines, and tried to push it back here, but it seems I need permissions for it. So I thought, I should just create an issue for it then. 

Thank you and have a good day,

Nik

**Comment by bushblade** [comment]
Hi @nikbrunner 
The code in the master branch should stay like it is for students to reference in the course.
Can you test your code against the [hookfix branch](https://github.com/bradtraversy/contact-keeper/tree/hookfix)? This is the branch that has been refactored to make better use of hooks with context.

**Comment by nikbrunner** [comment]
Hi @bushblade,
of course, I did not want to push directly on to the master branch. That's why I created a _fix_ branch which I wanted to push to the repo, for which I can create a PR then. GitFlow style.

In the mentioned hookfix branch, the `loading` [prop is also missing](https://github.com/bradtraversy/contact-keeper/blob/53db228fa02e2f97c2ec456a07fac2983538d9be/client/src/context/contact/ContactState.js#L129). I will try it out and check back.

**Comment by nikbrunner** [comment]
Now this is on the hookfix branch. You can see that initially `loading` is undefined and always falsy and after the load, the `contactReducer` sets `loading: false`, which I think happens, because it just adds it as a _new_ property to the `ContactState`.

<img width="1755" alt="Screenshot 2020-06-11 at 22 09 04" src="https://user-images.githubusercontent.com/46924729/84434442-57d1db00-ac30-11ea-9f0c-61b83744d8b2.png">

I committed it locally. Should I push it?

**Comment by bushblade** [comment]
You should fork the hookfix branch and make a pull request.
