### ISSUE TITLE
503 Service Unavailable on Heroku

### ISSUE THREAD

**Issue by notom** [bradtraversy/contact-keeper#26]
Deployed the app to heroku, but has no connection to the api:

https://protected-wave-43252.herokuapp.com

When I try to login or any other api routes it returns:
503 Service Unavailable

**Comment by bushblade** [comment]
Hi @notom 
I know this is a late reply, but I don't think this an issue with the repository code.
If you're one of Brad's students and are having issues in deploying your project to Heroku, then please post in the course Q&A and one of us will be able to help you out.
One thing to check though is that your database is not whitelisting any IP addresses. You can't have a static IP address on the free tier for Heroku, so you need to allow any IP access to your MongoDB atlas.
I'll close here as an issue.
