### ISSUE TITLE
Delete contact is not working.

### ISSUE THREAD

**Issue by russiandobby** [bradtraversy/contact-keeper#5]
I have tried everything.
```
   const deleteContact = async id => {
     
        try {
          await axios.delete(`/api/contacts/${id}`);
    
          dispatch({
            type: DELETE_CONTACT,
            payload: id
          });
        } catch (err) {
          dispatch({
            type: CONTACT_ERROR,
            payload: err.response.msg
          });
        }
      };
```

I have checked, when  pressing delete button it calls ondelete with the correct id, that passes it to the the contactState, and to axios, however after axios runs i check the database and the contacts is still there it's not being deleted from it. Anyone had similar issue

**Comment by abdelrhmanwahdan** [comment]
I have found a solution replace the delete function with this one in the routes folder contacts.js in the backend
`router.delete('/:id', (req, res, next) => {
  Contact.deleteOne({ _id: req.params.id })
    .then(() => {
      res.status(200).json({
        message: 'Deleted!'
      });
    })
    .catch(error => {
      res.status(400).json({
        error: error
      });
    });
});`

**Comment by Smokyn** [comment]
Thx bro, it works.

**Comment by amirsaa** [comment]
I had this problem too and I used delete route in this file to fix it:

https://github.com/bradtraversy/contact_keeper_api/blob/master/routes/contacts.js#L110
